spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rocketmq?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
